stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw/train.csv
    - data/raw/test.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/raw/train.csv
    - data/raw/test.csv
    params:
    - feature_engineering.n_components
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv

  train_model:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - data/processed/train_processed.csv
    params:
    - model_training.n_estimators
    - model_training.max_depth
    - model_training.bootstrap
    - model_training.criterion
    outs:
    - model.pkl

  evaluate_model:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - data/processed/test_processed.csv
    - model.pkl
    params:
    - feature_engineering.n_components
    - model_training.n_estimators
    - model_training.max_depth
    - model_training.bootstrap
    - model_training.criterion
    metrics:
    - metrics.json


params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
